import type { AppConfig } from "../src/config/env.js";

export function createTestConfig(
  overrides: Partial<AppConfig> = {},
): AppConfig {
  return {
    telegramBotToken: "token",
    telegramApiBaseUrl: "https://api.telegram.org",
    telegramPollingTimeoutSeconds: 30,
    telegramAllowedUserIds: [],
    copilotModel: "gpt-5",
    copilotCliPath: "copilot",
    copilotLogLevel: "info",
    copilotRequestTimeoutMs: 180_000,
    copilotDelegatedRequestTimeoutMs: 120_000,
    appUserStateRoot: "C:\\temp",
    skillsCommand: "npx",
    skillsAgent: "github-copilot",
    skillInstallTimeoutMs: 180_000,
    delegatedJobTimeoutMs: 240_000,
    messageQueueTimeoutMs: 300_000,
    googleWorkspaceCliCommand: undefined,
    googleWorkspaceCliArgs: [],
    gmailStatusArgs: [],
    gmailListArgs: [],
    gmailReadArgs: [],
    gmailSendArgs: [],
    gmailCommandTimeoutMs: 30_000,
    homeMateApiBaseUrl: undefined,
    homeMateApiToken: undefined,
    homeMateApiTokenHeader: "Authorization",
    homeMateApiTokenPrefix: "Bearer ",
    homeMateApiHeaders: {},
    homeMateApiTimeoutMs: 15_000,
    homeMateListSwitchesPath: "/devices",
    homeMateGetSwitchPath: "/devices/{deviceId}",
    homeMateSetSwitchStatePath: "/devices/{deviceId}",
    homeMateSetSwitchStateMethod: "PATCH",
    homeMateSetSwitchStateBodyTemplate: '{"state":"{state}"}',
    homeMateBulkSetSwitchStatePath: undefined,
    homeMateBulkSetSwitchStateMethod: "POST",
    homeMateBulkSetSwitchStateBodyTemplate:
      '{"deviceIds":{deviceIdsJson},"state":"{state}"}',
    homeMateAllowedSwitchIds: [],
    fileSearchRoots: ["C:\\"],
    fileSearchExcludedRoots: [],
    fileSearchMaxResults: 10,
    fileSearchContentExtensions: [
      ".txt",
      ".md",
      ".json",
      ".csv",
      ".log",
      ".pdf",
    ],
    fileSearchContentMaxFileSizeBytes: 1_000_000,
    fileSendMaxFileSizeBytes: 10 * 1024 * 1024,
    webcamCaptureCommand: undefined,
    webcamCaptureArgs: [],
    webcamCaptureTimeoutMs: 120_000,
    fileSearchAliases: {
      adhar: ["aadhaar", "aadhar"],
      aadhaar: ["adhar", "aadhar"],
      aadhar: ["aadhaar", "adhar"],
    },
    fileSearchMaxDurationMs: 15_000,
    fileSearchMaxFilesScanned: 20_000,
    ...overrides,
  };
}
